# Generated by Django 5.1.1 on 2024-09-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_userslist_mailing', 'can view userslist mailing'), ('can_disable_user_mailing', 'can disable user mailing'), ('can_view_any_mailing', 'can view any mailing lists'), ('can_disable_mailing', 'can disable mailing'), ('can_not_update_mailing_and_message', 'cannot edit mailing and message'), ('can_not_manage_mailing', 'cannot manage mailing'), ('can_not_edit_mailing', 'cannot edit mailing')], 'verbose_name': 'настройки', 'verbose_name_plural': 'настройки'},
        ),
    ]
