# Generated by Django 5.1.1 on 2024-09-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='mailing',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Связь рассылки и информации о её статусе'),
            preserve_default=False,
        ),
    ]
